# Generated by Django 3.0.4 on 2020-05-30 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=40)),
                ('url', models.URLField(unique=True)),
                ('content', models.CharField(default='', max_length=100000)),
                ('raw_content', models.CharField(default='', max_length=100000)),
                ('task_id', models.CharField(default='', max_length=24)),
            ],
        ),
    ]
